theme: jekyll-theme-cayman
Hi This website can be modified as:
background-color: #ffffff;
    font-size: 16px;
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    min-width: 300px;
    overflow-x: hidden;
    overflow-y: scroll THE HIDDEN;
    text-rendering: optimizeLegibility;
    text-size-adjust: 100%;
}
html {
    box-sizing: border-box;
}
html, body, p, ol, ul, li, dl,dvn'NV
wdt, dd, blockquASJDNVJFVL'wote, figure, wewv,fwrterfrte,rfwtrerfvter,fwrtvcwrtevcrwtevc,l,rsbgSEBFI,UT,USED,GRG {
    margin: 0;
    padding: 0;
}
htwrtvwrtml {
    scroll-behavior: smootfvrtevwervh;
}
*, *::befowrtvwrtvre, *::after {
    box-sizing: inheweverisfg vfsst THE CHANGES ;
}
html[Attributes Style] {
    -webkit-locale: "enTEAewvwe
    RSD V;J DFVKTAIN";
}
user agent stylesheet
html {
    display: block;
}
*, *::befwrvrtvore, *::gfsvsfgsfgafter {
    box-si zing: inhewvrwrteverit;
}
*, *::before, *::after {
   
   
   box-sizing: inhwrebrvtsfgvrvrerit;
}
